/**
 * @author Dawid Cokan
 * 
 * This script initialize user with its default tablespace and all neccessary (
 * and probably more :) ) rights. 
 * 
 * Execute it as following:
 * sqlplus SYSTEM/SYSTEM @000_Init_user.sql
 * and next
 *  sqlplus IT_APP_USER/IT_APP @001_TABLES.sql

 * **In case if You have different SYSTEM user password use it instead
 * ** You have to copy file into some directory and run above statement from that directory
 */

CREATE BIGFILE TABLESPACE IT_APP_DB
	 DATAFILE 'IT_APP_TAB.dat'
	 SIZE 100M
	 AUTOEXTEND ON;


CREATE USER IT_APP_USER IDENTIFIED BY IT_APP
	DEFAULT TABLESPACE "IT_APP_DB";
	
GRANT CREATE SESSION TO "IT_APP_USER";
GRANT ALTER TABLESPACE TO "IT_APP_USER" ;
GRANT DROP ANY TRIGGER TO "IT_APP_USER" ;
GRANT CREATE USER TO "IT_APP_USER" ;
GRANT CREATE ANY OUTLINE TO "IT_APP_USER" ;
GRANT FLASHBACK ANY TABLE TO "IT_APP_USER" ;
GRANT ALTER ANY SEQUENCE TO "IT_APP_USER" ;
GRANT ALTER ANY LIBRARY TO "IT_APP_USER" ;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO "IT_APP_USER" ;
GRANT CREATE MINING MODEL TO "IT_APP_USER" ;
GRANT UPDATE ANY TABLE TO "IT_APP_USER" ;
GRANT UPDATE ANY CUBE TO "IT_APP_USER" ;
GRANT CREATE TRIGGER TO "IT_APP_USER" ;
GRANT DROP ANY EVALUATION CONTEXT TO "IT_APP_USER" ;
GRANT DROP PROFILE TO "IT_APP_USER" ;
GRANT CREATE TABLESPACE TO "IT_APP_USER" ;
GRANT DEBUG CONNECT SESSION TO "IT_APP_USER" ;
GRANT DROP ANY DIRECTORY TO "IT_APP_USER" ;
GRANT CREATE ASSEMBLY TO "IT_APP_USER" ;
GRANT SELECT ANY CUBE TO "IT_APP_USER" ;
GRANT CREATE SEQUENCE TO "IT_APP_USER" ;
GRANT ON COMMIT REFRESH TO "IT_APP_USER" ;
GRANT SELECT ANY SEQUENCE TO "IT_APP_USER" ;
GRANT CREATE ANY SQL PROFILE TO "IT_APP_USER" ;
GRANT DROP ANY SQL PROFILE TO "IT_APP_USER" ;
GRANT ADMINISTER ANY SQL TUNING SET TO "IT_APP_USER" ;
GRANT ADVISOR TO "IT_APP_USER" ;
GRANT ALTER ANY MINING MODEL TO "IT_APP_USER" ;
GRANT EXECUTE ANY OPERATOR TO "IT_APP_USER" ;
GRANT ALTER PROFILE TO "IT_APP_USER" ;
GRANT EXECUTE ANY TYPE TO "IT_APP_USER" ;
GRANT CREATE ANY DIRECTORY TO "IT_APP_USER" ;
GRANT CREATE TABLE TO "IT_APP_USER" ;
GRANT CREATE ANY INDEX TO "IT_APP_USER" ;
GRANT ADMINISTER RESOURCE MANAGER TO "IT_APP_USER" ;
GRANT BECOME USER TO "IT_APP_USER" ;
GRANT MANAGE TABLESPACE TO "IT_APP_USER" ;
GRANT DROP ANY MINING MODEL TO "IT_APP_USER" ;
GRANT EXECUTE ASSEMBLY TO "IT_APP_USER" ;
GRANT SELECT ANY TABLE TO "IT_APP_USER" ;
GRANT DROP ROLLBACK SEGMENT TO "IT_APP_USER" ;
GRANT CREATE OPERATOR TO "IT_APP_USER" ;
GRANT ALTER ANY CUBE TO "IT_APP_USER" ;
GRANT ALTER PUBLIC DATABASE LINK TO "IT_APP_USER" ;
GRANT CREATE ANY PROCEDURE TO "IT_APP_USER" ;
GRANT CREATE ANY CUBE TO "IT_APP_USER" ;
GRANT DROP ANY INDEXTYPE TO "IT_APP_USER" ;
GRANT SELECT ANY MINING MODEL TO "IT_APP_USER" ;
GRANT EXECUTE ANY CLASS TO "IT_APP_USER" ;
GRANT CREATE ANY MATERIALIZED VIEW TO "IT_APP_USER" ;
GRANT SELECT ANY TRANSACTION TO "IT_APP_USER" ;
GRANT ANALYZE ANY DICTIONARY TO "IT_APP_USER" ;
GRANT CREATE EXTERNAL JOB TO "IT_APP_USER" ;
GRANT INSERT ANY TABLE TO "IT_APP_USER" ;
GRANT CREATE LIBRARY TO "IT_APP_USER" ;
GRANT GRANT ANY OBJECT PRIVILEGE TO "IT_APP_USER" ;
GRANT CREATE JOB TO "IT_APP_USER" ;
GRANT CREATE ANY OPERATOR TO "IT_APP_USER" ;
GRANT ALTER ANY RULE TO "IT_APP_USER" ;
GRANT CREATE ANY LIBRARY TO "IT_APP_USER" ;
GRANT CREATE ANY SEQUENCE TO "IT_APP_USER" ;
GRANT DROP PUBLIC SYNONYM TO "IT_APP_USER" ;
GRANT CREATE CLUSTER TO "IT_APP_USER" ;
GRANT FORCE ANY TRANSACTION TO "IT_APP_USER" ;
GRANT UPDATE ANY CUBE DIMENSION TO "IT_APP_USER" ;
GRANT CREATE EVALUATION CONTEXT TO "IT_APP_USER" ;
GRANT CREATE ANY CUBE BUILD PROCESS TO "IT_APP_USER" ;
GRANT DROP ANY OPERATOR TO "IT_APP_USER" ;
GRANT DROP USER TO "IT_APP_USER" ;
GRANT EXECUTE ANY INDEXTYPE TO "IT_APP_USER" ;
GRANT ALTER ANY EDITION TO "IT_APP_USER" ;
GRANT LOCK ANY TABLE TO "IT_APP_USER" ;
GRANT DROP ANY TYPE TO "IT_APP_USER" ;
GRANT CHANGE NOTIFICATION TO "IT_APP_USER" ;
GRANT CREATE ANY DIMENSION TO "IT_APP_USER" ;
GRANT DROP ANY DIMENSION TO "IT_APP_USER" ;
GRANT READ ANY FILE GROUP TO "IT_APP_USER" ;
GRANT CREATE ANY RULE TO "IT_APP_USER" ;
GRANT ALTER ANY ASSEMBLY TO "IT_APP_USER" ;
GRANT EXEMPT IDENTITY POLICY TO "IT_APP_USER" ;
GRANT ALTER ROLLBACK SEGMENT TO "IT_APP_USER" ;
GRANT CREATE RULE TO "IT_APP_USER" ;
GRANT CREATE ANY VIEW TO "IT_APP_USER" ;
GRANT CREATE PROCEDURE TO "IT_APP_USER" ;
GRANT INSERT ANY MEASURE FOLDER TO "IT_APP_USER" ;
GRANT ANALYZE ANY TO "IT_APP_USER" ;
GRANT ALTER ANY TYPE TO "IT_APP_USER" ;
GRANT DROP ANY EDITION TO "IT_APP_USER" ;
GRANT CREATE ANY TRIGGER TO "IT_APP_USER" ;
GRANT MANAGE ANY FILE GROUP TO "IT_APP_USER" ;
GRANT DROP ANY RULE TO "IT_APP_USER" ;
GRANT CREATE DIMENSION TO "IT_APP_USER" ;
GRANT CREATE ROLLBACK SEGMENT TO "IT_APP_USER" ;
GRANT FLASHBACK ARCHIVE ADMINISTER TO "IT_APP_USER" ;
GRANT ALTER ANY RULE SET TO "IT_APP_USER" ;
GRANT DROP ANY SEQUENCE TO "IT_APP_USER" ;
GRANT DROP ANY TABLE TO "IT_APP_USER" ;
GRANT CREATE CUBE DIMENSION TO "IT_APP_USER" ;
GRANT EXECUTE ANY RULE TO "IT_APP_USER" ;
GRANT DROP ANY LIBRARY TO "IT_APP_USER" ;
GRANT EXECUTE ANY PROCEDURE TO "IT_APP_USER" ;
GRANT DROP ANY VIEW TO "IT_APP_USER" ;
GRANT DROP ANY CONTEXT TO "IT_APP_USER" ;
GRANT FORCE TRANSACTION TO "IT_APP_USER" ;
GRANT CREATE ANY JOB TO "IT_APP_USER" ;
GRANT DROP ANY ROLE TO "IT_APP_USER" ;
GRANT DELETE ANY CUBE DIMENSION TO "IT_APP_USER" ;
GRANT DROP ANY CLUSTER TO "IT_APP_USER" ;
GRANT UPDATE ANY CUBE BUILD PROCESS TO "IT_APP_USER" ;
GRANT CREATE ANY INDEXTYPE TO "IT_APP_USER" ;
GRANT ADMINISTER SQL TUNING SET TO "IT_APP_USER" ;
GRANT EXECUTE ANY PROGRAM TO "IT_APP_USER" ;
GRANT DROP ANY ASSEMBLY TO "IT_APP_USER" ;
GRANT ALTER DATABASE LINK TO "IT_APP_USER" ;
GRANT GRANT ANY PRIVILEGE TO "IT_APP_USER" ;
GRANT ALTER ANY PROCEDURE TO "IT_APP_USER" ;
GRANT MERGE ANY VIEW TO "IT_APP_USER" ;
GRANT CREATE ANY EVALUATION CONTEXT TO "IT_APP_USER" ;
GRANT ALTER ANY OPERATOR TO "IT_APP_USER" ;
GRANT ALTER ANY CUBE DIMENSION TO "IT_APP_USER" ;
GRANT COMMENT ANY MINING MODEL TO "IT_APP_USER" ;
GRANT ALTER ANY ROLE TO "IT_APP_USER" ;
GRANT EXECUTE ANY ASSEMBLY TO "IT_APP_USER" ;
GRANT CREATE CUBE BUILD PROCESS TO "IT_APP_USER" ;
GRANT EXECUTE ANY RULE SET TO "IT_APP_USER" ;
GRANT ALTER ANY TRIGGER TO "IT_APP_USER" ;
GRANT UNDER ANY TABLE TO "IT_APP_USER" ;
GRANT BACKUP ANY TABLE TO "IT_APP_USER" ;
GRANT CREATE SYNONYM TO "IT_APP_USER" ;
GRANT DROP ANY CUBE BUILD PROCESS TO "IT_APP_USER" ;
GRANT DROP ANY CUBE TO "IT_APP_USER" ;
GRANT ALTER DATABASE TO "IT_APP_USER" ;
GRANT ALTER ANY TABLE TO "IT_APP_USER" ;
GRANT CREATE VIEW TO "IT_APP_USER" ;
GRANT EXECUTE ANY LIBRARY TO "IT_APP_USER" ;
GRANT CREATE RULE SET TO "IT_APP_USER" ;
GRANT EXEMPT ACCESS POLICY TO "IT_APP_USER" ;
GRANT CREATE ANY CLUSTER TO "IT_APP_USER" ;
GRANT DROP ANY INDEX TO "IT_APP_USER" ;
GRANT CREATE TYPE TO "IT_APP_USER" ;
GRANT EXECUTE ANY EVALUATION CONTEXT TO "IT_APP_USER" ;
GRANT ALTER RESOURCE COST TO "IT_APP_USER" ;
GRANT ALTER ANY CLUSTER TO "IT_APP_USER" ;
GRANT ALTER ANY INDEX TO "IT_APP_USER" ;
GRANT CREATE PUBLIC SYNONYM TO "IT_APP_USER" ;
GRANT CREATE ANY MINING MODEL TO "IT_APP_USER" ;
GRANT GLOBAL QUERY REWRITE TO "IT_APP_USER" ;
GRANT CREATE ANY RULE SET TO "IT_APP_USER" ;
GRANT CREATE MEASURE FOLDER TO "IT_APP_USER" ;
GRANT DROP ANY CUBE DIMENSION TO "IT_APP_USER" ;
GRANT CREATE ROLE TO "IT_APP_USER" ;
GRANT RESTRICTED SESSION TO "IT_APP_USER" ;
GRANT DROP ANY PROCEDURE TO "IT_APP_USER" ;
GRANT ALTER USER TO "IT_APP_USER" ;
GRANT CREATE ANY CONTEXT TO "IT_APP_USER" ;
GRANT CREATE ANY SYNONYM TO "IT_APP_USER" ;
GRANT CREATE ANY CUBE DIMENSION TO "IT_APP_USER" ;
GRANT ALTER ANY OUTLINE TO "IT_APP_USER" ;
GRANT ENQUEUE ANY QUEUE TO "IT_APP_USER" ;
GRANT CREATE ANY TABLE TO "IT_APP_USER" ;
GRANT SELECT ANY CUBE DIMENSION TO "IT_APP_USER" ;
GRANT ALTER ANY EVALUATION CONTEXT TO "IT_APP_USER" ;
GRANT CREATE SESSION TO "IT_APP_USER" ;
GRANT DEQUEUE ANY QUEUE TO "IT_APP_USER" ;
GRANT QUERY REWRITE TO "IT_APP_USER" ;
GRANT EXPORT FULL DATABASE TO "IT_APP_USER" ;
GRANT CREATE PUBLIC DATABASE LINK TO "IT_APP_USER" ;
GRANT RESUMABLE TO "IT_APP_USER" ;
GRANT UNLIMITED TABLESPACE TO "IT_APP_USER" ;
GRANT UNDER ANY VIEW TO "IT_APP_USER" ;
GRANT DROP ANY OUTLINE TO "IT_APP_USER" ;
GRANT CREATE ANY EDITION TO "IT_APP_USER" ;
GRANT CREATE ANY ASSEMBLY TO "IT_APP_USER" ;
GRANT ALTER ANY INDEXTYPE TO "IT_APP_USER" ;
GRANT DROP ANY MATERIALIZED VIEW TO "IT_APP_USER" ;
GRANT CREATE INDEXTYPE TO "IT_APP_USER" ;
GRANT ALTER ANY SQL PROFILE TO "IT_APP_USER" ;
GRANT ALTER SYSTEM TO "IT_APP_USER" ;
GRANT DROP ANY SYNONYM TO "IT_APP_USER" ;
GRANT GRANT ANY ROLE TO "IT_APP_USER" ;
GRANT CREATE MATERIALIZED VIEW TO "IT_APP_USER" ;
GRANT DROP ANY RULE SET TO "IT_APP_USER" ;
GRANT MANAGE SCHEDULER TO "IT_APP_USER" ;
GRANT DROP TABLESPACE TO "IT_APP_USER" ;
GRANT SELECT ANY DICTIONARY TO "IT_APP_USER" ;
GRANT IMPORT FULL DATABASE TO "IT_APP_USER" ;
GRANT DELETE ANY MEASURE FOLDER TO "IT_APP_USER" ;
GRANT DELETE ANY TABLE TO "IT_APP_USER" ;
GRANT AUDIT SYSTEM TO "IT_APP_USER" ;
GRANT ALTER ANY MATERIALIZED VIEW TO "IT_APP_USER" ;
GRANT DEBUG ANY PROCEDURE TO "IT_APP_USER" ;
GRANT CREATE PROFILE TO "IT_APP_USER" ;
GRANT CREATE ANY MEASURE FOLDER TO "IT_APP_USER" ;
GRANT UNDER ANY TYPE TO "IT_APP_USER" ;
GRANT COMMENT ANY TABLE TO "IT_APP_USER" ;
GRANT ALTER ANY DIMENSION TO "IT_APP_USER" ;
GRANT CREATE ANY TYPE TO "IT_APP_USER" ;
GRANT DROP ANY MEASURE FOLDER TO "IT_APP_USER" ;
GRANT DROP PUBLIC DATABASE LINK TO "IT_APP_USER" ;
GRANT CREATE CUBE TO "IT_APP_USER" ;
GRANT CREATE DATABASE LINK TO "IT_APP_USER" ;
GRANT INSERT ANY CUBE DIMENSION TO "IT_APP_USER" ;
GRANT ALTER SESSION TO "IT_APP_USER" ;
GRANT MANAGE ANY QUEUE TO "IT_APP_USER" ;
GRANT ADMINISTER DATABASE TRIGGER TO "IT_APP_USER" ;
GRANT AUDIT ANY TO "IT_APP_USER" ;
GRANT MANAGE FILE GROUP TO "IT_APP_USER" ;

ALTER USER "IT_APP_USER" QUOTA UNLIMITED ON IT_APP_DB;