
CREATE TABLE PRODUCTS(
	ID NUMBER(5) NOT NULL,
	NAME VARCHAR2(50) NOT NULL, 
	PRICE DECIMAL(7,2) NOT NULL, 
	TYPE VARCHAR2(1) NOT NULL,
	DELETED VARCHAR2(1) DEFAULT 'N' NOT NULL
);

CREATE TABLE PRODUCTS_ORDERS_MAP(
	PRODUCT_ID NUMBER(5) NOT NULL,
	ORDER_ID NUMBER(5) NOT NULL
);

CREATE TABLE ORDERS(
	ID NUMBER(5) NOT NULL, 
	STATE VARCHAR2(1),
	PRICE DECIMAL(7,2),
	TABLE_ID NUMBER(5),
	ADULT_ONLY VARCHAR2(1)
);


CREATE TABLE RESOURCES(
	ID NUMBER(5) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	MEAS_UNIT VARCHAR2(2) NOT NULL,
	AMOUNT DECIMAL(7,2) NOT NULL,
	PRICE DECIMAL(7,2) NOT NULL
);

CREATE TABLE PRODUCT_RESOURCES_MAP(
	PRODUCT_ID NUMBER(5) NOT NULL,
	RESOURCE_ID NUMBER(5) NOT NULL,
	AMOUNT DECIMAL(7,2) NOT NULL
);

CREATE TABLE PRODUCT_RESTAURANT_MAP(
	PRODUCT_ID NUMBER(5) NOT NULL,
	RESTAURANT_ID NUMBER(5) NOT NULL
);

 CREATE TABLE USERS(
	ID NUMBER(5) NOT NULL,
	LOGIN VARCHAR2(20) NOT NULL,
	FIRSTNAME VARCHAR2(15),
	LASTNAME VARCHAR2(25),
	MAIL VARCHAR2(30) NOT NULL,
	TEL VARCHAR2(20),
	USER_PASS_HASH NOT NULL,
	LAST_LOGIN DATE,
	DELETED VARCHAR2(1),
	EMPL_TYPE VARCHAR2(1) NOT NULL,
	CREATOR NUMBER(5)
 );
 
 CREATE TABLE RESTAURANTS(
 	ID NUMBER(5) NOT NULL,
 	NAME VARCHAR2(40) NOT NULL,
 	STREET VARCHAR2(20) NOT NULL,
 	CITY VARCHAR2(20) NOT NULL,
 	POSTCODE VARCHAR2(20),
 	TEL1 VARCHAR2(20),
 	TEL2 VARCHAR2(20),
 	MAIL VARCHAR2(30),
 	OWNER_ID NUMBER(5) NOT NULL,
 	DELETED VARCHAR2(1) NOT NULL,
 	DESCRIPTION VARCHAR2(100)
 );
 
 CREATE TABLE RESTAURANT_TYPES(
 	ID NUMBER(5) NOT NULL,
 	NAME VARCHAR2(2) NOT NULL
 );
 